### ISSUE TITLE
what to do with buildyourowninter.net?

### ISSUE THREAD

**Issue by paidforby** [sudomesh/bugs#10]
We recently acquired the domain, buildyourowninter.net. This is a place to put suggestions, discussion, and development notes until we have a website or repository.

Some initial suggestions include:
* mediaWiki, a la https://sudoroom.org/wiki/Mesh
* gulp, a la https://disaster.radio
* a jekyll site, https://jekyllrb.com/
* ikea-style, hand-drawn, pictographic instructions

Whoever feels inclined could also just create a wiki or a repo and work on it!

**Comment by sierkje** [comment]
Are there already any ideas about the content we want on buildyourowninter.net?

**Comment by sierkje** [comment]
I created a repo for this here: https://github.com/sudomesh/buildyourinter.net

It's empty for now, but ideas could be filed as issues over there also: https://github.com/sudomesh/buildyourinter.net/issues/new

**Comment by paidforby** [comment]
I think content will mostly be guides, documentation, and infographics. Also it should be collaborative as possible, right? Not sure if a statically generated site suits this? Would something with a CMS, login, etc, be better?

**Comment by paidforby** [comment]
Also another good question to think about, who is the target audience? Other mesh projects? community members? journalists? all of the above?

**Comment by sierkje** [comment]
I don't whether a CMS, a wiki, or a static site generator is best for this. It depends all on the content. That's why I was asking about that.

But if it should be "as collaborative as possible" when it comes to creating content, then yes, I'd use a CMS of some sort. But even if we'd eventually end up using a CMS, it very well could still be a good plan to use jekyll or mediawiki initially, while fleshing out the content.

**Comment by paidforby** [comment]
buildyourowninter.net is now online and is being developed under buildyourowninternet org's repo https://github.com/buildyourowninternet/buildyourowninternet.github.io. Issues, advice, complaints should be directed there.
